spring:
  application:
    name: dubbo-consumer
server:
  port: 8081
dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
  protocol:
    id: dubbo
    name: dubbo
  registry:
    id: my-registry
    address: 127.0.0.1:2181
    client: curator
    protocol: zookeeper
    check: true
    timeout: 60000
  monitor:
    protocol: registry