spring:
  application:
    name: dubbo-provider
server:
  port: 9090
dubbo:
  scan:
    base-packages: com.yibo.provider.service
  application:
    id: dubbo-provider
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: my-registry
    address: 127.0.0.1:2181
    client: curator
    protocol: zookeeper
    check: true
    timeout: 60000
  #对简易监控中心有用
  monitor:
    protocol: registry