spring:
  application:
    name: dubbo-provider
server:
  port: 9090
dubbo:
  scan:
    base-packages: com.yibo.provider.service
  application:
    id: dubbo-provider
    name: dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
  registry:
    id: my-registry
    address: zookeeper://127.0.0.1:2181
    client: curator