spring:
  application:
    name: another-provider
server:
  port: 9091
dubbo:
  scan:
    base-packages: com.yibo.anotherprovider.service
  application:
    id: another-provider
    name: another-provider
    qos-port: 22222
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
    status: server
  registry:
    id: another-registry
    address: 127.0.0.1:2181
    client: curator
    protocol: zookeeper
    check: true
    timeout: 60000
  monitor:
    protocol: registry
